// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw45tfxN_ihA_a73wTWbtJXPZGI545mQ0',
    appId: '1:1055091207699:web:60d02b2137ce39fd9c99e6',
    messagingSenderId: '1055091207699',
    projectId: 'nilcom-8fff5',
    authDomain: 'nilcom-8fff5.firebaseapp.com',
    storageBucket: 'nilcom-8fff5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKwIhpvrRSE7e1ZMFW_GECYSKtmgTkPso',
    appId: '1:1055091207699:android:3c30cded75c193699c99e6',
    messagingSenderId: '1055091207699',
    projectId: 'nilcom-8fff5',
    storageBucket: 'nilcom-8fff5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4-v464fLhf8n_1J4UvPkls1QU7lCeZ1s',
    appId: '1:1055091207699:ios:e6a8e4a3227fe37e9c99e6',
    messagingSenderId: '1055091207699',
    projectId: 'nilcom-8fff5',
    storageBucket: 'nilcom-8fff5.appspot.com',
    iosBundleId: 'com.example.nilcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4-v464fLhf8n_1J4UvPkls1QU7lCeZ1s',
    appId: '1:1055091207699:ios:9b87d238378a1b959c99e6',
    messagingSenderId: '1055091207699',
    projectId: 'nilcom-8fff5',
    storageBucket: 'nilcom-8fff5.appspot.com',
    iosBundleId: 'com.example.nilcom.RunnerTests',
  );
}
